backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["news"] }
      - {
          label: "Hero Image",
          name: "heroImage",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Author",
          name: "author",
          widget: "select",
          options: ["Alan", "Zack"],
          default: "Alan",
        }
  - name: "recipe" # Used in routes, e.g., /admin/collections/blog
    label: "Recipe" # Used in the UI
    folder: "src/content/recipe" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - {
          label: "Hero Image",
          name: "heroImage",
          widget: "image",
          required: false,
        }
      - { label: "Ingredients", name: "ingredients", widget: "markdown" }
      - { label: "Steps", name: "steps", widget: "markdown" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "review" # Used in routes, e.g., /admin/collections/blog
    label: "Review" # Used in the UI
    folder: "src/content/review" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - {
          label: "Hero Image",
          name: "heroImage",
          widget: "image",
          required: false,
        }
      - { label: "Website", name: "website", widget: "string" }
      - { label: "Address", name: "address", widget: "string" }
      - { label: "Latitude", name: "latitude", widget: "string" }
      - { label: "Longitude", name: "longitude", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

media_folder: "public/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads"
site_url: "https://alanandzack.netlify.app/"
